Repository Accenture/sfmc-devtools, pull requests merged in 2021-12, with the labels that each got.

#135 features #130 return json of all available components + #64 retrieve AccountUser
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .issuetracker
  CHANGELOG.md
  README.md
  boilerplate/config.json
  docs/dist/documentation.md
  lib/MetadataTypeDefinitions.js
  lib/MetadataTypeInfo.js
  lib/Retriever.js
  lib/cli.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/definitions/AccountUser.definition.js
  lib/metadataTypes/definitions/DataExtension.definition.js
  lib/retrieveChangelog.js
  lib/util/cli.js
  lib/util/init.git.js
  package-lock.json
  package.json
Labels: enhancement

#143 Bugfix/asset types
  lib/metadataTypes/Asset.js
  lib/metadataTypes/definitions/Asset.definition.js
Labels: bug, enhancement

#150 #149: filter out empty responses
  CHANGELOG.md
  lib/metadataTypes/DataExtension.js
Labels: bug

#151 Develop
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug.yml
  .issuetracker
  .vscode/settings.json
  CHANGELOG.md
  README.md
  boilerplate/config.json
  docs/dist/documentation.md
  img/README.md/troubleshoot-nodejs-postinstall.jpg
  lib/Deployer.js
  lib/MetadataTypeDefinitions.js
  lib/MetadataTypeInfo.js
  lib/Retriever.js
  lib/cli.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/definitions/AccountUser.definition.js
  lib/metadataTypes/definitions/Asset.definition.js
  lib/metadataTypes/definitions/DataExtension.definition.js
  lib/metadataTypes/definitions/ImportFile.definition.js
  lib/metadataTypes/definitions/Script.definition.js
  lib/retrieveChangelog.js
  lib/util/cli.js
  lib/util/init.git.js
  lib/util/util.js
  package-lock.json
  package.json
  postinstall.js
Labels: bug, enhancement
