Repository Accenture/sfmc-devtools, pull requests merged in 2022-04, with the labels that each got.

#245 Breaking Change: #244 option to document of standard roles (default: off) + `document` parameters order changed to mirror other commands
  README.md
  boilerplate/config.json
  docs/dist/documentation.md
  lib/cli.js
  lib/metadataTypes/Role.js
Labels: enhancement

#250 Task/94 replace update notifier git
  docs/dist/documentation.md
  lib/index.js
  lib/util/cli.js
  lib/util/devops.js
  lib/util/file.js
  lib/util/init.config.js
  lib/util/init.git.js
  lib/util/init.js
  lib/util/init.npm.js
  lib/util/util.js
  package-lock.json
  package.json
Labels: chore, dependencies

#246 #254 + #251 + #242 + #208 asset-asset javacript error / asset-message data loss / asset-message email attributes supported
  docs/dist/documentation.md
  lib/cli.js
  lib/index.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/definitions/Asset.definition.js
  lib/util/file.js
  lib/util/util.js
Labels: bug, enhancement

#256 Bugfix/255 mocha dependency causes install failure on some linux servers
  .eslintrc.json
  package-lock.json
  package.json
  test/util/file.js
Labels: bug, dependencies

#258 #257 + #17 skip interaction does not throw error on config issues + correct exit code sent to CI/CD
  .github/ISSUE_TEMPLATE/bug.yml
  .github/PULL_REQUEST_TEMPLATE.md
  docs/dist/documentation.md
  lib/cli.js
  lib/index.js
  lib/util/util.js
  package.json
Labels: bug, enhancement, e/DevOps

#261 #260: use path sep to avoid system issues
  lib/index.js
Labels: bug

#264 #263: Fixes to deploy of Import FIle to all subs
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/definitions/ImportFile.definition.js
Labels: bug, c/importFile

#265 Chore: #180 check blueprint files for changes before trying to override them during upgrade
  docs/dist/documentation.md
  lib/util/init.config.js
Labels: chore

#270 Bugfix/259 smaller issues around create delta pkg and deploy
  docs/dist/documentation.md
  lib/index.js
  lib/util/util.js
Labels: bug

#272 #271: upgrade copyright notice to current year & add support URL
  LICENSE
  lib/cli.js
  lib/util/init.git.js
Labels: chore

#273 #267: retrieveAsTemplate broken for `dataExtract` activity
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/FileTransfer.js
Labels: bug, c/dataExtract, c/fileTransfer

#274 Task/172 option to force update of specific config files if we made crucial changes
  boilerplate/forcedUpdates.json
  docs/dist/documentation.md
  lib/util/init.config.js
  lib/util/init.js
Labels: chore

#278 Task/277 task eslint typechecks
  .eslintrc.json
  docs/dist/documentation.md
  lib/Builder.js
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/AttributeGroup.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/Campaign.js
  lib/metadataTypes/ContentArea.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtensionTemplate.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/DataExtractType.js
  lib/metadataTypes/Discovery.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Filter.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/FtpLocation.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/Interaction.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/MobileCode.js
  lib/metadataTypes/MobileKeyword.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/SetDefinition.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/retrieveChangelog.js
  lib/util/businessUnit.js
  lib/util/cache.js
  lib/util/cli.js
  lib/util/devops.js
  lib/util/file.js
  lib/util/init.config.js
  lib/util/init.git.js
  lib/util/init.js
  lib/util/init.npm.js
  lib/util/util.js
  package-lock.json
  package.json
Labels: chore

#280 Task/279 speed up lint:fix and commit hook
  lib/util/cache.js
  package.json
Labels: chore
