Repository Accenture/sfmc-devtools, pull requests merged in 2022-07, with the labels that each got.

#350 Task/346 only upsert metadata that was actually changed
  docs/dist/documentation.md
  lib/metadataTypes/Folder.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/definitions/Folder.definition.js
  package-lock.json
  package.json
  types/mcdev.d.js
Labels: enhancement, c/folder

#361 Task/final checks 4.0.0
  docs/dist/documentation.md
  lib/Builder.js
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/definitions/DataExtract.definition.js
  lib/util/auth.js
  lib/util/devops.js
  lib/util/init.js
  lib/util/util.js
  package-lock.json
  package.json
  test/mockRoot/.mcdevrc.json
Labels: chore

#362 Task/356 4.0.0 dependencies
  .github/PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: chore

#366 Task/363 enable eslint plugin unicorn
  .eslintrc.json
  lib/Builder.js
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/retrieveChangelog.js
  lib/util/businessUnit.js
  lib/util/cache.js
  lib/util/cli.js
  lib/util/config.js
  lib/util/devops.js
  lib/util/file.js
  lib/util/init.config.js
  lib/util/init.git.js
  lib/util/init.js
  lib/util/init.npm.js
  lib/util/util.js
  package-lock.json
  package.json
  test/resourceFactory.js
  test/utils.js
Labels: chore

#365 Task/364 improve log readability
  lib/Deployer.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/ContentArea.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/Discovery.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/metadataTypes/definitions/Automation.definition.js
  lib/util/cache.js
  package.json
Labels: chore

#368 #367: Fix to use new error handling
  lib/metadataTypes/MetadataType.js
Labels: bug

#370 Feature/125 ensure eslint + prettier are installed with the same version in the project as in mcdev
  boilerplate/files/.npmrc
  boilerplate/npm-dependencies.json
  lib/util/config.js
  lib/util/init.npm.js
  lib/util/util.js
Labels: enhancement
