Repository Accenture/sfmc-devtools, pull requests merged in 2022-01, with the labels that each got.

#153 [Task] #152 code ql and dependabot configuration added
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  lib/util/cli.js
Labels: chores

#158 [TASK] #157 change dependabot target
  .github/dependabot.yml
Labels: chores

#171 Hotfix/i168 bug retrieveAsTemplate bug when using filename prefixes and suffixes
  docs/dist/documentation.md
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Script.js
  package-lock.json
  package.json
Labels: bug, c/automation, c/dataExtension, c/dataExtract, c/eventDefinition, c/importFile, c/query, c/script, PRIORITY, c/fileTransfer

#165 #34 add delete support
  README.md
  docs/dist/documentation.md
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/AttributeGroup.js
  lib/metadataTypes/Campaign.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/FtpLocation.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/Interaction.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/SetDefinition.js
  lib/metadataTypes/TriggeredSendDefinition.js
Labels: enhancement

#186 #185 - Fix "this._setLoggingLevel is not a function" bug when running mcdev createDeltaPkg
  lib/cli.js
  lib/index.js
Labels: bug
