Repository Accenture/sfmc-devtools, pull requests merged in 2022-02, with the labels that each got.

#174 [Feature]#159 mobilekeywords
  README.md
  lib/MetadataTypeDefinitions.js
  lib/MetadataTypeInfo.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/MobileCode.js
  lib/metadataTypes/MobileKeyword.js
  lib/metadataTypes/definitions/MobileCode.definition.js
  lib/metadataTypes/definitions/MobileKeyword.definition.js
  lib/util/util.js
Labels: enhancement, e/Metadata support, c/smsActivity, call needed

#194 Bugfix/187 mcdev bdb fails to find template where name and key differ
  README.md
  docs/dist/documentation.md
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/MetadataType.js
  lib/util/devops.js
  lib/util/util.js
Labels: bug, PRIORITY

#190 Feature/188 move retry logic
  docs/dist/documentation.md
  lib/Deployer.js
  lib/Retriever.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/MetadataType.js
  lib/util/util.js
  package-lock.json
  package.json
Labels: e/Core

#191 Task/189 extract cache class
  docs/dist/documentation.md
  lib/Builder.js
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/AttributeGroup.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/Campaign.js
  lib/metadataTypes/ContentArea.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/DataExtractType.js
  lib/metadataTypes/Discovery.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/FtpLocation.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/Interaction.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/MobileCode.js
  lib/metadataTypes/MobileKeyword.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/SetDefinition.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/util/cache.js
  lib/util/devops.js
  lib/util/init.git.js
  lib/util/util.js
Labels: e/Core

#193 Support spring22 scope
  lib/util/util.js
  package-lock.json
  package.json
Labels: e/Core

#201 #200 fix error on scope tests
  lib/util/util.js
Labels: bug

#203 #202 fix numeric keys not accepted
  lib/metadataTypes/MetadataType.js
Labels: bug
