Repository Accenture/sfmc-devtools, pull requests merged in 2022-05, with the labels that each got.

#292 Bugfix: #290 mcdev init fails to add 2nd credential + #291mcdev init breaks on updating BUs
  docs/dist/documentation.md
  lib/util/cli.js
  lib/util/util.js
Labels: bug

#287 Task/286 move type definitions into separate files
  .eslintrc.json
  docs/dist/documentation.md
  jsconfig.json
  lib/Builder.js
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/AttributeGroup.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/Campaign.js
  lib/metadataTypes/ContentArea.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtensionTemplate.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/DataExtractType.js
  lib/metadataTypes/Discovery.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Filter.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/FtpLocation.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/Interaction.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/MobileCode.js
  lib/metadataTypes/MobileKeyword.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/SetDefinition.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/util/cache.js
  lib/util/cli.js
  lib/util/init.git.js
  lib/util/util.js
  types/mcdev.d.js
Labels: chore

#285 Feature: #281 make retrievechangelog available for all types
  README.md
  docs/dist/documentation.md
  lib/Deployer.js
  lib/Retriever.js
  lib/cli.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/definitions/Asset.definition.js
  lib/metadataTypes/definitions/Automation.definition.js
  lib/metadataTypes/definitions/DataExtension.definition.js
  lib/metadataTypes/definitions/DataExtract.definition.js
  lib/metadataTypes/definitions/EmailSendDefinition.definition.js
  lib/metadataTypes/definitions/EventDefinition.definition.js
  lib/metadataTypes/definitions/FileTransfer.definition.js
  lib/metadataTypes/definitions/Filter.definition.js
  lib/metadataTypes/definitions/FtpLocation.definition.js
  lib/metadataTypes/definitions/ImportFile.definition.js
  lib/metadataTypes/definitions/Interaction.definition.js
  lib/metadataTypes/definitions/MobileCode.definition.js
  lib/metadataTypes/definitions/MobileKeyword.definition.js
  lib/metadataTypes/definitions/Query.definition.js
  lib/metadataTypes/definitions/Role.definition.js
  lib/metadataTypes/definitions/Script.definition.js
  lib/metadataTypes/definitions/SetDefinition.definition.js
  lib/metadataTypes/definitions/TriggeredSendDefinition.definition.js
  lib/util/util.js
  package-lock.json
  test/dataExtension.test.js
  test/query.test.js
Labels: enhancement, e/DevOps

#289 Feature/288 allow retrieving+deploying multiple types via cli command
  README.md
  docs/dist/documentation.md
  lib/Deployer.js
  lib/index.js
  lib/util/util.js
Labels: e/Core

#296 Bugfix/295 dataextension fields not properly formatted in retrieve-folder after de-create
  .github/PULL_REQUEST_TEMPLATE.md
  lib/metadataTypes/DataExtension.js
  lib/util/util.js
  test/dataExtension.test.js
  test/resources/9999999/dataExtension/create-expected.json
  test/resources/9999999/dataExtension/update-expected.json
  test/utils.js
Labels: bug, c/dataExtension

#298 Task/297 auto format new types file
  .eslintrc.json
  docs/dist/documentation.md
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/AttributeGroup.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/Campaign.js
  lib/metadataTypes/ContentArea.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtensionTemplate.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/DataExtractType.js
  lib/metadataTypes/Discovery.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Filter.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/FtpLocation.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/Interaction.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/MobileCode.js
  lib/metadataTypes/MobileKeyword.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/SetDefinition.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/retrieveChangelog.js
  lib/util/businessUnit.js
  lib/util/cli.js
  lib/util/devops.js
  lib/util/file.js
  lib/util/init.config.js
  lib/util/init.git.js
  lib/util/init.js
  lib/util/init.npm.js
  lib/util/util.js
  package-lock.json
  package.json
  test/resourceFactory.js
  test/utils.js
  types/mcdev.d.js
Labels: chore

#268 BREAKING CHANGE #252: retrieve with new auth
  .eslintrc.json
  README.md
  boilerplate/config.json
  docs/dist/documentation.md
  lib/Builder.js
  lib/Deployer.js
  lib/Retriever.js
  lib/index.js
  lib/metadataTypes/DataExtension.js
  lib/util/auth.js
  lib/util/businessUnit.js
  lib/util/cli.js
  lib/util/file.js
  lib/util/init.config.js
  lib/util/init.git.js
  lib/util/init.js
  lib/util/util.js
  test/dataExtension.test.js
  test/mockRoot/.mcdev-auth.json
  test/query.test.js
  test/utils.js
  types/mcdev.d.js
Labels: chore

#309 #308: enhance how multi-file metadata is presented in VSCode
  boilerplate/files/.vscode/settings.json
  docs/dist/documentation.md
  lib/metadataTypes/DataExtension.js
Labels: e/IDE, chore

#299 Feature/19 add buildtemplate based on rt command that uses retrieve folder and not server as source
  .eslintrc.json
  README.md
  docs/dist/documentation.md
  lib/Builder.js
  lib/cli.js
  lib/index.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Script.js
  lib/util/util.js
  test/dataExtension.test.js
  test/query.test.js
  types/mcdev.d.js
Labels: enhancement, e/Core, e/DevOps, PRIORITY, c/Generic

#305 Feature/73 add document automation for auditing
  README.md
  boilerplate/config.json
  docs/dist/documentation.md
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/definitions/Automation.definition.js
  lib/util/init.config.js
  test/mockRoot/.mcdevrc.json
  types/mcdev.d.js
Labels: enhancement, e/Auditing, c/automation

#315 #314: SFMC-SDK dep bump
  package-lock.json
  package.json
Labels: dependencies

#301 Feature: #18 include buildtemplate in createdeltapkg + #300 no more key-name swapping in rt
  boilerplate/config.json
  docs/dist/documentation.md
  lib/Builder.js
  lib/index.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Script.js
  lib/util/devops.js
  lib/util/init.config.js
  lib/util/util.js
  types/mcdev.d.js
Labels: enhancement, e/DevOps, PRIORITY

#323 #320: Test Methods inverted and fixed
  lib/Builder.js
  lib/Retriever.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/Campaign.js
  lib/metadataTypes/DataExtract.js
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/MobileKeyword.js
  lib/util/auth.js
  lib/util/devops.js
  lib/util/file.js
  test/dataExtension.test.js
  test/query.test.js
  test/resources/9999999/query/build-expected.json
Labels: bug

#307 Feature/302 get list of extracted files for given type+key
  docs/dist/documentation.md
  lib/Builder.js
  lib/Deployer.js
  lib/cli.js
  lib/index.js
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Role.js
  lib/metadataTypes/Script.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/util/devops.js
  lib/util/file.js
  lib/util/init.config.js
  lib/util/util.js
Labels: enhancement, e/DevOps, c/asset, c/query, c/script, PRIORITY
