Repository Accenture/sfmc-devtools, pull requests merged in 2022-03, with the labels that each got.

#212 #210: Resolves issues with update of Roles
  lib/index.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Role.js
Labels: bug

#217 Bugfix/216 bug econnreset not caught by sdk
  lib/util/util.js
  package-lock.json
  package.json
Labels: bug

#221 #219 inform user about field retrieve after deploy of dataExtension
  lib/metadataTypes/DataExtension.js
Labels: bug, c/dataExtension

#226 #225 correcting spelling error that prevents mobileX to work on linux
  lib/MetadataTypeDefinitions.js
Labels: bug, c/mobileCode, c/mobileKeyword

#218 #213 ensure docs/roles file is not overwritten during role deploy
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/definitions/Role.definition.js
Labels: bug, c/role

#220 #214 ensure that errors in preDeployTasks are handled gracefully
  docs/dist/documentation.md
  lib/metadataTypes/EventDefinition.js
  lib/metadataTypes/FileTransfer.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/MetadataType.js
Labels: bug, c/eventDefinition, c/folder, c/fileTransfer

#227 Bump fs-extra from 10.0.0 to 10.0.1
  package-lock.json
  package.json
Labels: dependencies

#228 Bump inquirer from 8.2.0 to 8.2.2
  package-lock.json
  package.json
Labels: dependencies

#229 Bump lint-staged from 12.3.4 to 12.3.7
  package-lock.json
  package.json
Labels: dependencies

#230 Bump mocha from 9.2.1 to 9.2.2
  package-lock.json
  package.json
Labels: dependencies

#231 Bump eslint from 8.9.0 to 8.12.0
  package-lock.json
  package.json
Labels: dependencies

#232 Bump eslint-config-prettier from 8.4.0 to 8.5.0
  package-lock.json
  package.json
Labels: dependencies

#233 Bump prettier from 2.5.1 to 2.6.1
  package-lock.json
  package.json
Labels: dependencies

#234 Bump yargs from 17.3.1 to 17.4.0
  package-lock.json
  package.json
Labels: dependencies

#235 Bump simple-git from 3.2.6 to 3.5.0
  package-lock.json
  package.json
Labels: dependencies

#224 Bugfix/215 deploy email send definition fails badly if dependent asset is missing
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/ImportFile.js
  lib/metadataTypes/Query.js
  lib/metadataTypes/Script.js
Labels: bug, c/emailSendDefinition, c/importFile, c/query, c/script

#237 Bugfix/236 retrieve for more than 2500 records fails soap
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/ContentArea.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/DataExtensionField.js
  lib/metadataTypes/DataExtensionTemplate.js
  lib/metadataTypes/Email.js
  lib/metadataTypes/EmailSendDefinition.js
  lib/metadataTypes/Folder.js
  lib/metadataTypes/List.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/TriggeredSendDefinition.js
  lib/util/util.js
Labels: bug, c/accountUser, c/dataExtension, c/emailSendDefinition, c/list, c/triggeredSendDefinition, c/email, c/contentArea

#238 Feature/stop retrieve on exception
  lib/Retriever.js
Labels: enhancement

#241 Bugfix/240 document broken due to new SDKs true booleans
  lib/metadataTypes/AccountUser.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/Role.js
Labels: bug, c/accountUser, c/dataExtension, c/role
