Repository Accenture/sfmc-devtools, pull requests merged in 2023-06, with the labels that each got.

#952 #951: fix test for user-documentation
  test/type.user.test.js
Labels: chore, c/Testing

#919 Feature/730 feature execute query command
  docs/dist/documentation.md
  lib/cli.js
  lib/index.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  test/resourceFactory.js
  test/resources/9999999/automation/v1/queries/549f0568-607c-4940-afef-437965094dat/actions/start/post-response.txt
  test/type.query.test.js
Labels: enhancement, c/query

#956 #734: run document on postDeploy of automation
  lib/metadataTypes/Automation.js
Labels: bug, c/automation

#953 Task/844 add test class for automation
  docs/dist/documentation.md
  lib/Deployer.js
  lib/index.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/DataExtension.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/definitions/Automation.definition.js
  lib/util/devops.js
  test/mockRoot/deploy/testInstance/testBU/automation/testExisting_automation.automation-meta.json
  test/mockRoot/deploy/testInstance/testBU/automation/testNew_automation.automation-meta.json
  test/mockRoot/deploy/testInstance/testBU/query/testExisting_query.query-meta.json
  test/mockRoot/deploy/testInstance/testBU/query/testExisting_query.query-meta.sql
  test/mockRoot/deploy/testInstance/testBU/query/testNew_query.query-meta.json
  test/mockRoot/deploy/testInstance/testBU/query/testNew_query.query-meta.sql
  test/resourceFactory.js
  test/resources/9999999/automation/build-expected.json
  test/resources/9999999/automation/create-expected.json
  test/resources/9999999/automation/delete-response.xml
  test/resources/9999999/automation/retrieve-expected.json
  test/resources/9999999/automation/retrieve-testExisting_automation-expected.md
  test/resources/9999999/automation/retrieve-testNew_automation-expected.md
  test/resources/9999999/automation/template-expected.json
  test/resources/9999999/automation/update-expected.json
  test/resources/9999999/automation/v1/automations/08afb0e2-b00a-4c88-ad2e-1f7f8788c560/get-response.json
  test/resources/9999999/automation/v1/automations/08afb0e2-b00a-4c88-ad2e-1f7f8788c560/patch-response.json
  test/resources/9999999/automation/v1/automations/a8afb0e2-b00a-4c88-ad2e-1f7f8788c560/get-response.json
  test/resources/9999999/automation/v1/automations/post-response.json
  test/resources/9999999/automation/v1/dataextracts/56c5370a-f988-4f36-b0ee-0f876573f6d7/get-response.json
  test/resources/9999999/automation/v1/dataextracts/get-response.json
  test/resources/9999999/automation/v1/filetransfers/72c328ac-f5b0-4e37-91d3-a775666f15a6/get-response.json
  test/resources/9999999/automation/v1/filetransfers/get-response.json
  test/resources/9999999/automation/v1/imports/get-response.json
  test/resources/9999999/automation/v1/queries/549f0568-607c-4940-afef-437965094dat/get-response.json
  test/resources/9999999/automation/v1/queries/549f0568-607c-4940-afef-437965094dat/patch-response.json
  test/resources/9999999/automation/v1/queries/get-response.json
  test/resources/9999999/automation/v1/queries/post-response.json
  test/resources/9999999/automation/v1/scripts/get-response.json
  test/resources/9999999/dataFolder/retrieve-ContentType=automations-response.xml
  test/resources/9999999/dataFolder/retrieve-ContentType=queryactivity-response.xml
  test/resources/9999999/dataFolder/retrieve-response.xml
  test/resources/9999999/emailSendDefinition/retrieve-response.xml
  test/resources/9999999/program/retrieve-CustomerKey=testExisting_automation-response.xml
  test/resources/9999999/program/retrieve-CustomerKey=testNew_automation-response.xml
  test/resources/9999999/program/retrieve-Name=testExisting_automation-response.xml
  test/resources/9999999/program/retrieve-response.xml
  test/resources/9999999/query/build-expected.json
  test/resources/9999999/query/get-expected.json
  test/resources/9999999/query/get2-expected.json
  test/resources/9999999/query/patch-expected.json
  test/resources/9999999/query/post-expected.json
  test/resources/9999999/query/template-expected.json
  test/type.automation.test.js
  test/type.dataExtension.test.js
  test/type.query.test.js
  test/utils.js
Labels: c/automation, chore, c/Testing

#960 #959: contributors: ensure commit msg template ends on a space
  .husky/post-checkout
Labels: chore

#970 bugfix/964: define actual maxKeyLength per type for changeKeyX
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/definitions/Asset.definition.js
  lib/metadataTypes/definitions/Automation.definition.js
  lib/metadataTypes/definitions/DataExtension.definition.js
  lib/metadataTypes/definitions/DataExtract.definition.js
  lib/metadataTypes/definitions/EmailSend.definition.js
  lib/metadataTypes/definitions/Event.definition.js
  lib/metadataTypes/definitions/Filter.definition.js
  lib/metadataTypes/definitions/ImportFile.definition.js
  lib/metadataTypes/definitions/MobileKeyword.definition.js
  lib/metadataTypes/definitions/Query.definition.js
  lib/metadataTypes/definitions/Role.definition.js
  lib/metadataTypes/definitions/TriggeredSend.definition.js
  lib/metadataTypes/definitions/User.definition.js
Labels: bug

#971 bugfix/207: dont create logfile when running helper methods + bugfix/969: log not truncated during test execution
  docs/dist/documentation.md
  lib/Deployer.js
  lib/cli.js
  lib/index.js
  lib/util/util.js
  test/utils.js
Labels: bug

#974 Task/972 upgrade report nyc coverage GitHub action to v127
  .coverage-comment-template.md
  .coverage-comment-template.svelte
  .github/workflows/coverage-base-update.yml
  .github/workflows/coverage-develop-branch.yml
  .github/workflows/coverage-main-branch.yml
  .github/workflows/coverage.yml
Labels: chore

#976 #975: enable dependabot for github-actions
  .github/dependabot.yml
Labels: chore, github-action

#996 bugfix/991: group command-options in --help to make it easier to read
  lib/cli.js
Labels: chore

#992 bugfix/988 read refresh from options
  docs/dist/documentation.md
  lib/Deployer.js
  lib/metadataTypes/Asset.js
  lib/metadataTypes/Automation.js
  lib/metadataTypes/Event.js
  lib/metadataTypes/Journey.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/TriggeredSend.js
Labels: bug

#1004 bugfix/985: ensure trailing commas in key/type lists do not lead to unforeseen executions
  lib/cli.js
Labels: bug

#986 feature/982: added option to execute after deploy
  .eslintrc.json
  docs/dist/documentation.md
  lib/cli.js
  lib/index.js
  lib/metadataTypes/MetadataType.js
  lib/metadataTypes/Query.js
  test/resourceFactory.js
  test/resources/9999999/automation/v1/queries/549f0568-607c-4940-afef-437965094dae/actions/start/post-response.txt
  test/resources/9999999/queryDefinition/retrieve-CustomerKey=testExisting_queryANDStatus=Active-response.xml
  test/resources/9999999/queryDefinition/retrieve-CustomerKey=testNew_queryANDStatus=Active-response.xml
  test/type.query.test.js
Labels: enhancement

#1009 #1008: ensure deploy returns deployed items, not complete cache
  lib/util/cache.js
  test/type.user.test.js
Labels: bug

#1011 Task/1010 ensure test load more specific soap response files
  .eslintrc.json
  test/resourceFactory.js
  test/resources/1111111/accountUser/retrieve-ActiveFlag=falseANDCustomerKey=testExisting_userANDEmaillike@-response.xml
  test/resources/1111111/accountUser/retrieve-ActiveFlag=falseANDEmaillike@-response.xml
  test/resources/1111111/accountUser/retrieve-ActiveFlag=trueANDCustomerKey=testExisting_userANDEmaillike@-response.xml
  test/resources/1111111/accountUser/retrieve-ActiveFlag=trueANDEmailisNullORNamelikeapp userANDMustChangePassword=false-response.xml
  test/resources/1111111/accountUser/retrieve-ActiveFlag=trueANDEmaillike@-response.xml
  test/resources/1111111/accountUser/retrieve-CustomerKey=testExisting_userANDActiveFlag=trueANDEmailisNullORNamelikeapp userANDMustChangePassword=false-response.xml
  test/resources/1111111/accountUserAccount/retrieve-AccountUser.AccountUserID=700301950-response.xml
  test/resources/1111111/accountUserAccount/retrieve-AccountUser.AccountUserIDIN700301950,700301951,7471228-response.xml
  test/resources/1111111/businessUnit/retrieve-ID=1111111-response.xml
  test/resources/1111111/list/retrieve-CustomerKey=All SubscribersORListName=All Subscribers-response.xml
  test/resources/1111111/role/retrieve-IsPrivate=false-response.xml
  test/resources/1111111/user/retrieve-expected.md
  test/resources/9999999/dataExtension/retrieve-Name=testExisting_dataExtension-response.xml
  test/resources/9999999/dataExtensionField/retrieve-DataExtension.CustomerKey=testExisting_dataExtension-response.xml
  test/resources/9999999/dataExtensionField/retrieve-DataExtension.CustomerKey=testNew_dataExtensionORDataExtension.CustomerKey=testExisting_dataExtension-response.xml
  test/resources/9999999/emailSendDefinition/retrieve-IsPlatformObject=falseANDDescriptionnotEqualsSFSendDefinition-response.xml
  test/resources/9999999/triggeredSendDefinition/retrieve-TriggeredSendStatusINNew,Active,Inactive,Moved,Canceled-response.xml
  test/type.user.test.js
Labels: chore

#1013 #1012: fix potential security issue regarding passwords in log files
  lib/metadataTypes/User.js
Labels: chore
